name: release-please
on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}

    steps:
      - name: Mint GitHub App token
        id: get-github-app-token
        uses: grafana/shared-workflows/actions/create-github-app-token@259ba21cb3ff07724f331e26d926d655d24b317b # create-github-app-token/v0.2.3
        with:
          github_app: app-o11y-kwl-ci

      - uses: googleapis/release-please-action@64d83e95d898ede84e4555719aba555c3244d469
        id: release
        with:
          token: ${{ steps.get-github-app-token.outputs.token }}
          config-file: release-please-config.json
          manifest-file: release-please-manifest.json

      - name: log context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          NEEDS_CONTEXT: ${{ toJson(needs) }}
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "$NEEDS_CONTEXT"
          echo "$STEPS_CONTEXT"

  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    environment: npm-trusted-publishing
    needs: release-please
    permissions:
      contents: write
      id-token: write
    if: ${{ needs.release-please.outputs.releases_created }}
    steps:
      - id: get-secrets
        name: get secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@0a7a2fc07560de0f2fe500ed9fd1f53ec7d86d33
        with:
          repo_secrets: |
            NPM_TOKEN=npm:token

      - name: Checkout
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          persist-credentials: false
          ref: main

      - name: Enable corepack
        run: corepack enable

      - name: Setup .npmrc file for NPM registry
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238
        with:
          node-version: lts/*
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run tests
        run: |
          yarn build
          # Retry tests 3 times
          yarn test || yarn test || yarn test

      - name: Build production bundle
        run: yarn build

      - name: Publish package to NPM
        run: yarn run publish from-package --yes
